name: update_informer
description: Updating for informally.
version: 1.0.4
homepage: https://github.com/10urbulut/update_informer


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  store_redirect: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0


  # dart pub publish --dry-run
  # do version upgrade
  # dart pub publish