name: update_informer
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/10urbulut/
repository: https://github.com/10urbulut/update_informer/

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
  package_info_plus: ^3.0.3
  provider: ^6.0.5
  store_redirect: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:
