name: update_informer
description: Updating for informally.
version: 1.0.3
homepage: https://github.com/10urbulut/update_informer


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  provider: ^6.1.1
  store_redirect: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


  # dart pub publish --dry-run
  # do version upgrade
  # dart pub publish